[project]
name = "nfl-injury-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "scikit-learn>=1.4.1",
  "pandas>=2.2.1",
  "numpy>=1.26.4",
  "matplotlib>=3.8.3",
  "jupyterlab>=4.3.5",
]
